require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VolumesController do

  # This should return the minimal set of attributes required to create a valid
  # Volume. As you add validations to Volume, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VolumesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all volumes as @volumes" do
      volume = Volume.create! valid_attributes
      get :index, {}, valid_session
      assigns(:volumes).should eq([volume])
    end
  end

  describe "GET show" do
    it "assigns the requested volume as @volume" do
      volume = Volume.create! valid_attributes
      get :show, {:id => volume.to_param}, valid_session
      assigns(:volume).should eq(volume)
    end
  end

  describe "GET new" do
    it "assigns a new volume as @volume" do
      get :new, {}, valid_session
      assigns(:volume).should be_a_new(Volume)
    end
  end

  describe "GET edit" do
    it "assigns the requested volume as @volume" do
      volume = Volume.create! valid_attributes
      get :edit, {:id => volume.to_param}, valid_session
      assigns(:volume).should eq(volume)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Volume" do
        expect {
          post :create, {:volume => valid_attributes}, valid_session
        }.to change(Volume, :count).by(1)
      end

      it "assigns a newly created volume as @volume" do
        post :create, {:volume => valid_attributes}, valid_session
        assigns(:volume).should be_a(Volume)
        assigns(:volume).should be_persisted
      end

      it "redirects to the created volume" do
        post :create, {:volume => valid_attributes}, valid_session
        response.should redirect_to(Volume.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved volume as @volume" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volume.any_instance.stub(:save).and_return(false)
        post :create, {:volume => {  }}, valid_session
        assigns(:volume).should be_a_new(Volume)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volume.any_instance.stub(:save).and_return(false)
        post :create, {:volume => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested volume" do
        volume = Volume.create! valid_attributes
        # Assuming there are no other volumes in the database, this
        # specifies that the Volume created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Volume.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => volume.to_param, :volume => { "these" => "params" }}, valid_session
      end

      it "assigns the requested volume as @volume" do
        volume = Volume.create! valid_attributes
        put :update, {:id => volume.to_param, :volume => valid_attributes}, valid_session
        assigns(:volume).should eq(volume)
      end

      it "redirects to the volume" do
        volume = Volume.create! valid_attributes
        put :update, {:id => volume.to_param, :volume => valid_attributes}, valid_session
        response.should redirect_to(volume)
      end
    end

    describe "with invalid params" do
      it "assigns the volume as @volume" do
        volume = Volume.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Volume.any_instance.stub(:save).and_return(false)
        put :update, {:id => volume.to_param, :volume => {  }}, valid_session
        assigns(:volume).should eq(volume)
      end

      it "re-renders the 'edit' template" do
        volume = Volume.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Volume.any_instance.stub(:save).and_return(false)
        put :update, {:id => volume.to_param, :volume => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested volume" do
      volume = Volume.create! valid_attributes
      expect {
        delete :destroy, {:id => volume.to_param}, valid_session
      }.to change(Volume, :count).by(-1)
    end

    it "redirects to the volumes list" do
      volume = Volume.create! valid_attributes
      delete :destroy, {:id => volume.to_param}, valid_session
      response.should redirect_to(volumes_url)
    end
  end

end
